# Generated by Django 5.0.4 on 2024-04-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('patronymic', models.CharField(max_length=35)),
                ('birth_year', models.IntegerField()),
                ('group', models.CharField(max_length=20)),
            ],
        ),
    ]
